#!/usr/bin/env bash

_eclipse_workspace=$1

[[ -z $_eclipse_workspace ]] && exit 1
[[ ! -d $_eclipse_workspace ]] && exit 1

mvn -DdownloadSources=true -DdownloadJavadocs=true -DoutputDirectory=target/eclipse-classes -Declipse.workspace=$_eclipse_workspace eclipse:eclipse eclipse:add-maven-repo
